### ISSUE TITLE
Any cocoa pod support?

### ISSUE THREAD

**Issue by maksumon** [koher/easy-dl#7]
I would like to integrate this into my iOS project but it seems I cannot do that? Would anyone please let me know the integration process?

Thanks in advance.

**Comment by koher** [comment]
Hi. Please use [Carthage](https://github.com/Carthage/Carthage) to install EasyDL for iOS apps.

```bash
brew install carthage
cd path/to/your/project
echo 'github "koher/easy-dl" "0.2.0-alpha"' >> Cartfile
carthage update --platform ios
```

When it's done, you need to add the framework to your project manually.

https://github.com/Carthage/Carthage#adding-frameworks-to-an-application

**Comment by maksumon** [comment]
@koher thanks a lot for your suggestion. It worked following those processes.
